config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  resources :posts do
    collection do 
      post :confirm
    end
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    validates :content, presence: true, length: {maximum: 140, minimun:1}
    validates :title, presence: true, length: {maximum:10}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_secure_password
    before_validation {email.downcase!}
    validates :name, presence: true, length: {maximum: 30}
    validates :email, presence: true, uniqueness: true, length: {maximum: 255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  }
    validates :password, presence: true, length: {minimum:6}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required
    
    def login_required
      redirect_to new_session_path unless current_user
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = current_user.posts
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if params[:back]
      render :new
    elsif @post.save
      redirect_to posts_path, notice: "Post was successfully created." 
    else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
    end
  end
  

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def confirm 
    @post =Post.new(post_params)
    @post.user_id = current_user.id
    render :new if @post.invalid?
  end


  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :image, :image_cache)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    
  end
  def create 
    user =  User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
        redirect_to posts_path
    else
      flash.now[:danger] = "Email ou mot de passe incorrect !"
      render :new
    end
  end
  def destroy 
    session.delete(:user_id)
    flash[:notice] = 'Déconnection réussi !'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: [ :new, :create]

  

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit 
        if action_name == 'new' || action_name == 'create'
            confirm_posts_path 
        elsif action_name == 'edit'
            post_path 
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Facebook Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'header' %>
    <div class="container">
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>

        <%= yield %>
    </div>
    <%= render "footer" %>
</body>

</html>

app/views/posts/_footer.html.erb
<footer>
    <p> Dive Into Code &copy; 2021 Facebook App | Design by Gyll-christ DOKO ALFA</p>
</footer>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, url: choose_new_or_edit) do |form| %>
<% if post.errors.any? %>
<div id="error_explanation" class="py-2 text-light text-center bg-danger w-100">
    <h6><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h6>

    <ul class=" text-dark text-center bg-light">
        <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control"%>
</div>



<div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control"%>
</div>

<%
=begin%>
 <div class="field">
    <%= form.label :post_image %>
    <%= form.file_field :post_image, class: "form-control"%>
</div> 
<%
=end%>
<div class="field">
  <%= form.label :image %><br />
  <%= image_tag(post.image.url) if post.image && post.image.url %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>
</div>


<div class="actions m-3" style="float:right;">
    <%= form.submit %>
</div>
<% end %>

app/views/posts/_header.html.erb
<header>
    <nav class="navbar navbar-light bg-light p-3">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">Facebook Clone App</span>

            <div class="">

                <%= link_to 'View all posts', posts_path , class: "btn btn-outline-secondary"%>
                <%= link_to 'Publish', new_post_path , class: "btn btn-outline-primary"%>
            </div>
            <div>

                <% if logged_in? %>
                <%= link_to "Profile", user_path(current_user.id) , class: "btn btn-primary text-light"%>
                <%= link_to "Logout", session_path(current_user.id), method: :delete , class: "btn btn-danger text-light" %>
                <% else %>
                <%= link_to "Sign up", new_user_path , class: "btn btn-outline-primary text-light" %>
                <%= link_to "Login", new_session_path, class: "btn btn-outline-success text-light" %>
                <% end %>
            </div>
        </div>
    </nav>
</header>

app/views/posts/confirm.html.erb
<h3>Confirm this post</h3>



<%= form_with(model: @post, url: posts_path, local: true, method:'post') do |form| %>
<div class="field">
    <p>Title: <%= @post.title %></p>
    <%= form.hidden_field :title, class: "form-control"%>
</div>

<div class="field">
    <p>Description: <%= @post.content %></p>
    <%= form.hidden_field :content, class: "form-control"%>
</div>
<div class="field">
    <div class="card-img-top" style="width: 50%;">
  <%= image_tag(@post.image.url) if @post.image && @post.image.url%>
  </div>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Post" %>
<% end %>
<%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Return", name: "back" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: "btn btn-primary pt-2 mt-2" %>
<%= link_to 'Back', posts_path, class: "btn btn-outline-danger pt-2 mt-2" %>

app/views/posts/index.html.erb
 <h1>Posts</h1>
 <div class="row row-cols-1 row-cols-md-2 g-4">
     <% @posts.each do |post| %>
     <div class="col">
         <div class="card">
             <%= image_tag post.image.url, class: "card-img-top"%>
           


             <div class="card-body">

                 <h5 class="card-title"><%= post.title %></h5>

                 <p class="card-text"><%= post.content %></p>
             </div>
             <div class="card-footer clearfix ">
                 <small class="text-muted" style="float: right;"><%= post.created_at %></small>

                 <p><%= link_to 'Show', post, class: "btn btn-primary text-light" %></p>
                 <p><%= link_to 'Edit', edit_post_path(post), class: "btn btn-warning text-dar" %></p>
                 <p><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger text-light" %></p>
             </div>
         </div>
     </div>
     <% end %>
 </div>

app/views/posts/new.html.erb
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path, class: "btn btn-outline-danger pt-2 mt-2"%>

app/views/posts/show.html.erb
<h1>Post Detail</h1>
<div class="">
    <div class="card w-100">

        <%= image_tag @post.image.url, class: "card-img-top"%>

        <div class="card-body">

            <h5 class="card-title"><%= @post.title %></h5>


            <p class="card-text"><%= @post.content %></p>
        </div>
        <div class="card-footer clearfix">
            <small class="text-muted" style="float: right;"><%= @post.created_at %></small>

            <p><%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %></p>
            <p><%= link_to 'Back', posts_path , class: "btn btn-outline-secondary" %></p>
        </div>
    </div>
</div>

app/views/users/_footer.html.erb
<footer>
    <p> Dive Into Code &copy; 2021 Facebook App | Design by Gyll-christ DOKO ALFA</p>
</footer>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
<% if user.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
        <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , class: "form-control"%>
</div>

<div class="field">
    <%= form.label :email %>
    <%= form.email_field :email , class: "form-control"%>
</div>

<div class="field">
    <%= form.label :password %>
    <%= form.password_field :password , class: "form-control"%>
</div>
<div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation , class: "form-control"%>
</div>

<div class="actions" style="float:right;">
    <%= form.submit %>
</div>
<% end %>

app/views/users/_header.html.erb
<header>
    <nav class="navbar navbar-light bg-light p-3">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">Facebook Clone App</span>
            <% if logged_in? %>
            <div class="">

                <%= link_to 'View all posts', posts_path , class: "btn btn-outline-secondary"%>
                <%= link_to 'Publish', new_post_path , class: "btn btn-outline-primary"%>
            </div>
            <div>
                <%= link_to "Profile", user_path(current_user.id) , class: "btn btn-primary text-light"%>
                <%= link_to "Logout", session_path(current_user.id), method: :delete , class: "btn btn-danger text-light" %>
            </div>
            <% else %>
            <div>

                <%= link_to "Sign up", new_user_path , class: "btn btn-outline-primary mx-3", style: "float: right;" %>
                <%= link_to "Login", new_session_path, class: "btn btn-success text-light" %>

            </div>
            <% end %>
        </div>
    </nav>
</header>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user , class: "btn btn-outline-warning"%> |
<%= link_to 'Back', users_path, class: "btn btn-outline-danger" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container text-center">
    <p>
        <strong>Name:</strong>
        <%= @user.name %>
    </p>

    <p>
        <strong>Email:</strong>
        <%= @user.email %>
    </p>


    <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-warning" %> |
    <%= link_to 'Back', posts_path , class: "btn btn-danger"%>
</div>